name: Deploy App Python

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para deploy'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      debug_enabled:
        description: 'Habilitar debug'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt    

      - name: Gerar build (zip da aplicação)
        run: |
          mkdir build
          cp -r app.py requirements.txt templates build/
          cd build
          zip -r ../meuapp.zip .
          cd ..


  artefato:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: meuapp
          path: meuapp.zip

  deploy:
    needs: artefato
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKER_USER }}/meuapp:latest .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USER }}/meuapp:latest
